### ISSUE TITLE
Change - Color of the roster sections for Roundtable / across the website

### ISSUE THREAD

**Issue by SkyeGuy** [mjlyman23/91stSFG-Tracking#9]
**Provide a description of the feature**
Can we change the color of the "Delta" header to a delta force green (similar to the color in Discord, I think the hexadecimal value is 0A8F06, or whatever looks good with the existing color palette. 

We also should change the "Pending" header section to a nice vibrant red, and move that to the top of the page for the Master Roster for RT. Screenshot of the section below.

![capture](https://user-images.githubusercontent.com/20469914/43367424-984456c6-931a-11e8-8d26-2bd978c7da5f.PNG)

Change the header color to a palette-matching green, and move it down. Change Pending to red and put it at the top.

**Comment by mjlyman23** [comment]
done
